package com.mggx.laberinto.ui.icons

/**
 * Todos los iconos del juego se dibujan con vectores propios (Path/Canvas).
 * No se usa ningun emoji ni ningun set de iconos externo.
 */
enum class IconId {
    // --- objetos: consumibles
    ANTORCHA, LLAMA_AZUL, FRASCO, BURBUJA, HILO, BRUJULA, OJO, MAPA, PERGAMINO,
    TIZA, PICO, FANTASMA, IMAN, RELOJ, BENGALA, VENDA, ESCUDO, ALA, SEMILLA,
    ONDA, GOTA, ESTRELLA_SUERTE, SOMBRA, CRISTAL_TIEMPO, PAN,

    // --- objetos: mejoras
    BOTA, PULMON, CORAZON, FAROL, MOCHILA, ESPIRAL, CUADRICULA, CALAVERA,
    MANO, ROCA, PLUMA, CATALEJO, SACO_MONEDAS, HUELLA, CUERDA,

    // --- objetos: reliquias
    COLMILLO, AMBAR, ROSA_VIENTOS, LAGRIMA, NUDO, LUCIERNAGA, RUNA,
    TORRE_VIGIA, CORAZONES_GEMELOS, VETA, ESCAMA, DIAPASON,

    // --- objetos: poderes permanentes
    LINTERNA, GATEO, PEZUNA, VETA_DORADA, PICO_ETERNO, MAPA_GRABADO,
    LATIDO, SIGILO,

    // --- objetos: cosmeticos
    GUANTE, MALLA, CENIZA, CAZADOR, BRAZALETE,
    SKIN_MINERO, SKIN_VETERANO, SKIN_TECNICO, SKIN_CENIZA, SKIN_VETAGRIS, SKIN_ESPORA,
    TINTE_CALIDO, TINTE_AMBAR, TINTE_VERDE, TINTE_ROJO,

    // --- interfaz
    MONEDA_ECO, MONEDA_VETAGRIS, JUGAR, TIENDA, ENGRANAJE, LOGROS, ATRAS,
    PAUSA, MANDO, ALTAVOZ, NOTA_MUSICAL, VIBRACION, INFO, CANDADO, TILDE,
    MAS, TROFEO, CRONOMETRO, VIDA, AGUANTE, SALIDA, CERRAR, REINICIAR,
    CASA, ESTADISTICA, PANTALLA, IDIOMA, RESET, DEDO, EQUIPAR,
    FLECHA_ABAJO, CORRER, DIFICULTAD, AGACHARSE, ARRASTRARSE, SALTAR, DE_PIE,
    MULTIJUGADOR, RELOJ_ARENA
}
